### ISSUE TITLE
Hướng dẫn verify public address

### ISSUE THREAD

**Issue by holland-hng** [phanvantai/verify-public-address#1]
Hello, chào bạn

Mình đang có một task về làm việc login thông qua walletconnect, mình đã sử dụng lib public_address_wallet của bạn, khá là ổn. Sau đó mình muốn verify public address thì chưa rõ cách sử dụng. Mình đã thử example nhưng mà hình như nó không work, connector.createSession không trả về giá trị gì cả.

Mong nhận dc hồi âm từ bạn :v chúc bạn nhiều sức khoẻ

**Comment by phanvantai** [comment]
À, mobile app của mình dành cho user đã mua nft, cần verify đúng address thì mới cung cấp function nên mình viết lib để support verify connect từ wallet và lấy public address cho mobile app confirm thôi ạ. Chứ lib này không có implement transaction hay sign gì hơn nũa đâu ạ =))
Bạn có thể mô tả hơn bài toán của bạn xem mình có thể giúp được gì không

**Comment by holland-hng** [comment]
Mobile tụi mình dùng flutter

Step step bên mình là thế này:
1) lấy public address -> gửi lên server -> nhận về một ramdom string
2) dùng ramdom string để ký bên metamask

 Hiện tại mình bị kẹt ở khâu ký

**Comment by phanvantai** [comment]
> Mobile tụi mình dùng flutter
> 
> Step step bên mình là thế này:
> 
> 1. lấy public address -> gửi lên server -> nhận về một ramdom string
> 2. dùng ramdom string để ký bên metamask
> 
> Hiện tại mình bị kẹt ở khâu ký

À, muốn sign data thì phải dùng lib này ạ https://pub.dev/packages/walletconnect_dart và dùng EthereumWalletConnectProvider nhé ạ

**Comment by holland-hng** [comment]
:v mình cám ơn bạn
